dist: trusty
group: stable

language: node_js
node_js:
  - "8"

services:
  - redis-server
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ulc;'
  - mysql -u root ulc < database/data/mysql.sql

install:
  - npm install
  - npm run copy

before_script:
  - pwd
  - ls -al
  - node blessing
  
script:
  - NODE_ENV=travis npm test

after_success: npm run coverage

cache:
  directories:
    - "node_modules"

