dist: trusty
group: stable

language: node_js
node_js:
  - "8"

services:
  - redis-server
  - mysql

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ulc;'
  - mysql -e 'USE ulc;'
  - mysql -u root -p root < database/data/mysql.sql

install:
  - npm install
  - npm run copy

before_script:
  - pwd
  - ls -al
  - node blessing
  
script:
  - npm test

after_success: npm run coverage

cache:
  directories:
    - "node_modules"

