dist: trusty
group: stable

language: node_js
node_js:
  - "8"

services:
  - redis-server

install:
  - npm install
  - npm run copy

before_script:
  - pwd
  - ls -al
  - node blessing
  
script:
  - npm test

after_success: npm run coverage

cache:
  directories:
    - "node_modules"

