console.log()
console.log("                     _oo0oo_                   ")
console.log("                    o8888888o                  ")
console.log('                    88" . "88                  ')
console.log("                    (| -_- |)                  ")
console.log("                    0\\  =  /0                 ")
console.log("                  ___/`---'\\___               ")
console.log("                .' \\\\|     |// '.            ")
console.log("               / \\\\|||  :  |||// \\          ")
console.log("              / _||||| -:- |||||- \\           ")
console.log("             |   | \\\\\\  -  /// |   |        ")
console.log("             | \\_|  ''\\---/''  |_/ |         ")
console.log("             \\  .-\\__  '-'  ___/-. /         ")
console.log("           ___'. .'  /--.--\\  `. .'___        ")
console.log(`        ."" '<  '.___\\_<|>_/___.\\\` >' "".   `)
console.log("       | | :  `- \\\`.;`\\ _ /`;.`/ - ` : | |  ")
console.log("       \\  \\ `_.   \\_ __\\ /__ _/   .-` /  / ")
console.log("   =====`-.____`.___ \\_____/___.-`___.-'===== ")
console.log("                     `=---='                   ")
console.log()
console.log("   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ")
console.log()
console.log("             佛祖保佑         永无BUG            ")
console.log()